os: linux
dist: focal
language: python
python:
  - "3.8"
before_install:
  - sudo apt-get install tesseract-ocr
cache: pip
install:
  - pip install coverage
  - pip install -r requirements.txt
script:
  - coverage run -m unittest discover -v
after_success:
  - bash <(curl -s https://codecov.io/bash)

